# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticket_type', models.CharField(max_length=30)),
                ('entrants', models.IntegerField()),
                ('price', models.IntegerField()),
                ('code_img', models.ImageField(default=None, upload_to='portal/images/')),
            ],
        ),
    ]
