# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrecord',
            name='code_img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
